name: CI/CD Protheus Deploy

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted

    steps:
    - name: Checkout repositório
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

name: Atualizar repositório local
run: |
  cd /opt/git_protheus/protheus/
  git fetch origin
  git checkout main
  git pull origin main

name: Verificar arquivos modificados
id: arquivos
run: |
  cd /opt/git_protheus/protheus/
  ARQUIVOS=$(git diff --name-only origin/main...HEAD | grep -Ei '\.prw$|\.tlpp$' | xargs)
  if [ -z "$ARQUIVOS" ]; then
    echo "Nenhum arquivo .prw ou .tlpp modificado. Cancelando deploy."
    exit 0
  fi
  echo "arquivos=$ARQUIVOS" >> "$GITHUB_OUTPUT"

name: Parar serviços do ERP
run: bash /totvs/scripts/gerenciar_servicos.sh parar

name: Backup dos RPOs
run: |
  TIMESTAMP=$(date +%Y%m%d_%H%M)
  export TIMESTAMP
  export RPOORIGEM=$(ls -d /totvs/p12prd/apo/producao/** | sort | tail -n1)
  mkdir -p "/totvs/p12prd/apo/producao/${TIMESTAMP}_backup_inis"
  cp "$RPO_ORIGEM/tttm120.rpo" "/totvs/p12prd/apo/producao/${TIMESTAMP}_backup_inis/"
  cp "$RPO_ORIGEM/rpocustom.rpo" "/totvs/p12prd/apo/producao/${TIMESTAMP}_backup_inis/"

name: Modo exclusivo
run: bash /totvs/scripts/gerenciar_servicos.sh exclusivo

name: Criar novas pastas com timestamp
run: |
  TIMESTAMP=$(date +%Y%m%d_%H%M)
  for dir in producao solar faturamento; do
    mkdir -p "/totvs/p12prd/apo/$dir/$TIMESTAMP"
  done

name: Backup dos arquivos INI
run: |
  TIMESTAMP=$(date +%Y%m%d_%H%M)
  mkdir -p "/totvs/p12prd/apo/producao/${TIMESTAMP}_backupinis"
  for d in /totvs/p12prd/bin/appserver*; do
    for ini in appserver.ini appsrvlinux.ini; do
      [ -f "$d/$ini" ] && cp "$d/$ini" "/totvs/p12prd/apo/producao/${TIMESTAMP}_backupinis/$(basename $d)$ini"
    done
  done

name: Compilar arquivos alterados
run: |
  cd /totvs/p12prd/bin/appserver_compilar
  for file in ${{ steps.arquivos.outputs.arquivos }}; do
    ./appserver -compile -files="/opt/git_protheus/protheus/$file" \
                -includes="/opt/git_protheus/protheus/Includes" \
                -src="/opt/git_protheus/protheus" \
                -env=COMPILAR_PRD
  done

name: Copiar RPOs compilados para as novas pastas
run: |
  TIMESTAMP=$(date +%Y%m%d_%H%M)
  RPOORIGEM=$(ls -d /totvs/p12prd/apo/producao/** | sort | tail -n1)
  for dir in producao faturamento; do
    DEST="/totvs/p12prd/apo/$dir/$TIMESTAMP"
    cp "$RPO_ORIGEM/tttm120.rpo" "$DEST/"
    cp "$RPO_ORIGEM/rpocustom.rpo" "$DEST/"
  done

name: Atualizar arquivos INI
run: |
  TIMESTAMP=$(date +%Y%m%d%H%M)
  for d in /totvs/p12prd/bin/appserver; do
    for ini_file in "$d/appserver.ini"; do
      [ ! -f "$ini_file" ] && continue
      sed -i -E "s#SourcePath=./apo/(producao|faturamento)/.#SourcePath=/totvs/p12prd/apo/\1/$TIMESTAMP/#g" "$ini_file"
      sed -i -E "s#RPOCustom=./apo/(producao|faturamento)/.*#RPOCustom=/totvs/p12prd/apo/\1/$TIMESTAMP/rpocustom.rpo#g" "$ini_file"
    done
  done

name: Iniciar serviços do ERP
run: bash /totvs/scripts/gerenciar_servicos.sh iniciar

name: Finalizado com sucesso
run: echo "✅ Deploy finalizado com sucesso!"
